---
version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: dp2
      POSTGRES_PASSWORD: dp2
      POSTGRES_DB: DB_DP2 
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql